### PR TITLE
switch to Project.toml, bump version to 0.7

### PR DESCRIPTION
**Pull request by pfitzseb**

### CODE REVIEW

**Comment by porterjamesj** [comment]
Thanks!

**Comment by pfitzseb** [comment]
Would you mind tagging a new release (https://github.com/apps/juliateam-registrator and https://github.com/apps/julia-tagbot are useful for automating the process)?

**Comment by porterjamesj** [comment]
Hmm it looks like I don't have access to install those apps in the JuliaWeb organization. Maybe @aviks can?

**Comment by aviks** [comment]
These apps are already installed organisation wide, afaics

**Pull request merged**
