### PR TITLE
require julia 0.7.0-alpha

### PR DESCRIPTION
**Pull request by markmont**
Add full support for Julia 0.7.0-alpha, which will break Julia 0.6 and previous versions.  All tests pass.

I am submitting this patch for discussion, not necessarily for merging, or at least not into the main branch, since it will break support for older versions of Julia.

This patch removes all deprecation warnings, but it may make more sense to live with some of them until Julia 1.0 forces a change -- I think the only thing that _has_ to change for Julia 0.7.0-alpha is adding `AbstractTrees.children(elem::HTMLText) = ()` to `src/manipulation.jl`

This patch also attempts to fully adopt Pkg3, which it may not make sense to do yet.

This patch does not bump the version number, but that is something that should be done if any part of the patch is adopted.

Thoughts?

### CODE REVIEW

**Comment by markmont** [comment]
An important point I forgot: until the next version of AbstractTrees.jl is released, this patch requires (and uses) the master branch of AbstractTrees.jl.

**Comment by porterjamesj** [comment]
Wow, thank you for doing this! I have been dreading the 0.7/Pkg3 update work, really appreciate it.

I think I'd like to hold off on merging this until:

- [ ]  0.7 is officially released and we can depend on a released version rather than the alpha
- [ ]  AbstractTrees cuts a release that works with 0.7.
- [ ] The tests pass (from looking at Travis briefly I'm guessing the CI scripts just need to updated)
- [ ]  I understand how Pkg3 works a bit better 😅. I haven't been keeping up with it's development and I'd love to get to read some docs and understand it's model of the world.

I think a good plan is keep updated this PR as these things happen, and then merge it once everything's ready.

I'm fine with breaking support for older versions of Julia, since 0.7 is such a big release, and since there are older releases that folks on older versions can continue using.

**Comment by markmont** [comment]
Thanks for the reply!  That all sounds good.  I'll look into why Travis CI is failing and then reply here.  All unit tests (`julia test/runtests.jl`) do succeed, however.

**Comment by markmont** [comment]
@porterjamesj : I've made some changes based on tips in the Julia forums.  Although GitHub reports that the checks have failed, this is OK and things are now better than when I created the original PR:

- TravisCI: The tests for Julia 0.6.0 are failing (and this is expected) but, with my recent changes to the PR, the tests for Julia nightly are now succeeding.
- Appveyor: This only tests Julia 0.6.0, so the failures are expected.

Also...

[x] AbstractTrees has made an official release, 0.2.0, which is compatible with Julia 0.7.0.  This PR has been updated to use the new release.
[x] Julia 0.7.0 is out of alpha and into beta now, and there is an official effort to [upgrade as many packages as possible to work with Julia 0.7](https://discourse.julialang.org/t/ann-introducing-upgradathon-fridays/12047).

I don't think this satisfies all of the conditions you listed, but it is significant progress.

**Comment by porterjamesj** [comment]
@markmont sorry for long reply! Been on vacation for the last week and half. Looking great, thanks for your continued work on this. I'll try to take a deeper look soon and figure out what we still need to do to get this merged.

**Comment by markmont** [comment]
Is there anything I can do on my end to help get Gumbo.jl working with Julia 0.7.0 at this point?

[Julia 0.7.0 was officially released](https://discourse.julialang.org/t/julia-v0-7-0-has-been-released/13032) today.

[Julia 1.0.0-rc1 has also been released](https://discourse.julialang.org/t/julia-v1-0-rc1-is-now-available/13008) and it appears that the core developers intend to do an official release of 1.0 soon.

**Comment by porterjamesj** [comment]
No, this looks great now! Sorry for delayed reply.

I looked into Pkg3 a bit, and as far as I can tell the core devs want everyone to not generate the TOML files themselves, but rather wait until they make an ecosystem-wide set of automated PRs to updated everyone, using some sort of attobot-like system. So I think I'd like to merge everything here, but just without the Pkg3 changes. If you have time to remove them feel free, but if not no worries, I'll take care of it.

**Comment by markmont** [comment]
The initial version (c6c1148) contained Pkg3 changes, but the most recent commit (9ce71a) does not.

**Comment by porterjamesj** [comment]
Ahh sorry, I hadn't noticed! In that case, I think this looks great.

**Comment by porterjamesj** [comment]
Thanks for all your work on this, really appreciate it! I'll tag a release once tests pass so people can start using Gumbo on 0.7.

**Pull request merged**
